---
title: "Systematic Anatomical Parcellation of the Human Cortex"
author: "Evan Collins, Hari McGrath, Hitten P Zaveri, Xenophon Papademetris, Kun Wu, Dennis D Spencer"
date: "22 August 2021"
output:
  html_document:
   toc: yes
   toc_float:
     collapsed: no
  pdf_document:
    latex_engine : xelatex
---

<style type="text/css">
div.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

<style type="text/css">
  body{
  font-size: 14pt;
}
</style>

# Rationale

Current whole-brain cortical atlases present limitations for standardizing the reporting of neuroscience data relative to neuroanatomy. Functional parcellations are often not intuitive in their naming and parcellation structures, hindering their value in clinical conference settings. Parcellations defined according to micro- and macro-neuroanatomical features are commonly limited in their application by the imprecision of sub-gyral localizations due to high inter-individual anatomical variability. We aimed to address these limitations with the development of a whole-brain atlas of the cortex, systematically parcellated into approximately 1 cm sections along gyri according to common neuroanatomical landmarks and in keeping with the unit of localization in epilepsy surgery – the intracranial electrode. 

# Methods

The atlas was built on the MNI 152 template and was segmented into regions based on robust anatomical landmarks. Cortical boundaries were defined by correlating labelled images in Duvernoy’s Atlas of the Human Brain with cortical features on the MNI brain rendered in FSLeyes. ITK-SNAP was used to measure and label the 1 cm parcels along the three 2D windows (axial, coronal, and sagittal) before being rendered in 3D. A standardized nomenclature was defined for the parcels based on local common anatomy, and color coding was added to elucidate regional boundaries. We verified the accuracy of atlas localizations using Yale BioImage Suite to register T1 MRI images and intracranial electrode locations from 20 individuals to the MNI 152 brain. 

# Results 

We created a whole-brain atlas of the cortex with 692 parcels and 96 regions (Fig.). Each parcel has a unique code, indicating the gyrus and the centimeter increment where it lies along the gyrus. Each lobe has an associated color, and gyri within the lobe are variations on that color. On verification of the 2024 electrode contacts assessed for accuracy, the overall coregistration accuracy was 96.1% relative to common neuroanatomical landmarks, indicating a robust registration protocol that would reliably facilitate clinical communication of individual data. 

# Conclusions 

We have created a novel cortical atlas consisting of 692 parcels, each defined in relation to common neuroanatomical landmarks across many individuals. The atlas provides a standardized nomenclature for communicating locations in the brain to the nearest centimeter of cortex in research and clinical settings. The atlas is also a substrate for the organization of multimodal data into a database, with functional parameters in the brain localized to the level of a parcel. 

# Funding

Department of Neurosurgery, Yale School of Medicine


 




